#!/bin/bash

## #ddev-generated
## Description: Clear auto-save
## Usage: xb-autosave clear
## Example: ddev autosave clear   # Clear all auto-saves.
## Aliases: autosave,as
## ExecRaw: false
## Flags: []
## AutocompleteTerms: ["clear"]

clear_autosave() {
  drush sql:query "delete from key_value where collection='canvas.auto_save'" > /dev/null
}

# Process command arguments.
case "$1" in
  clear) clear_autosave ;;
  "") echo "Usage: ddev xb-autosave clear" >&2; exit 1 ;;
  *) echo "Invalid argument: $1" >&2; exit 1 ;;
esac
