#!/bin/bash

## #ddev-generated
## Description: Find errors and enforce conventions with Stylelint.
## Usage: xb-stylelint [fix]
## Example: ddev stylelint      # Find errors.\nddev stylelint fix  # Fix errors where possible.
## Aliases: stylelint,css
## ExecRaw: false
## Flags: []
## AutocompleteTerms: ["fix"]

cd "$DDEV_COMPOSER_ROOT/$DDEV_DOCROOT/modules/contrib/canvas" || exit 1

case "$1" in
  "fix") npm run lint:stylelint -- --fix ;;
  "") npm run lint:stylelint ;;
  *)
    echo "Invalid argument: $1"
    exit 1
    ;;
esac
